services:
  node1:
    build: .
    ports:
      - "11001:11000"  # HTTP port
      - "12001:12000"  # Raft port
    command: >
      ./raft-server 
      -id 1
      -haddr 0.0.0.0:11000
      -raddr 0.0.0.0:12000
      -peers 2=node2:12000,3=node3:12000,4=node4:12000,5=node5:12000
    networks:
      - raft-net

  node2:
    build: .
    ports:
      - "11002:11000"
      - "12002:12000"
    command: >
      ./raft-server 
      -id 2
      -haddr 0.0.0.0:11000
      -raddr 0.0.0.0:12000
      -peers 1=node1:12000,3=node3:12000,4=node4:12000,5=node5:12000
    networks:
      - raft-net

  node3:
    build: .
    ports:
      - "11003:11000"
      - "12003:12000"
    command: >
      ./raft-server 
      -id 3
      -haddr 0.0.0.0:11000
      -raddr 0.0.0.0:12000
      -peers 1=node1:12000,2=node2:12000,4=node4:12000,5=node5:12000
    networks:
      - raft-net

  node4:
    build: .
    ports:
      - "11004:11000"
      - "12004:12000"
    command: >
      ./raft-server 
      -id 4
      -haddr 0.0.0.0:11000
      -raddr 0.0.0.0:12000
      -peers 1=node1:12000,2=node2:12000,3=node3:12000,5=node5:12000
    networks:
      - raft-net

  node5:
    build: .
    ports:
      - "11005:11000"
      - "12005:12000"
    command: >
      ./raft-server 
      -id 5
      -haddr 0.0.0.0:11000
      -raddr 0.0.0.0:12000
      -peers 1=node1:12000,2=node2:12000,3=node3:12000,4=node4:12000
    networks:
      - raft-net

networks:
  raft-net:
    driver: bridge